<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<PackageId>TickerQ.EntityFrameworkCore</PackageId>
		<Description>Entity Framework Core integration for scheduling and persisting cron/time-based jobs using TickerQ.</Description>
		<PackageTags>$(PackageTags);efcore;entityframework</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TickerQ.Utilities\TickerQ.Utilities.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FlexLabs.EntityFrameworkCore.Upsert" Version="$(DotNetVersion)" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="$(DotNetVersion)" />
	</ItemGroup>
</Project>