<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <PackageId>TickerQ.Instrumentation.OpenTelemetry</PackageId>
    <Title>TickerQ OpenTelemetry Instrumentation</Title>
    <Description>OpenTelemetry instrumentation package for TickerQ job scheduler with distributed tracing support</Description>
    <PackageTags>$(PackageTags);OpenTelemetry;Tracing;Instrumentation;Distributed</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TickerQ.Utilities\TickerQ.Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry" Version="[1.15.3,)" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="[1.15.3,)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(DotNetAbstractionsVersion)" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(DotNetAbstractionsVersion)" />
  </ItemGroup>
</Project>
