namespace TickerQ.SourceGenerator.Generation
{
    /// <summary>
    /// Code generation templates. Each template uses {{PLACEHOLDER}} markers
    /// that are replaced at generation time with computed values.
    /// </summary>
    internal static class Templates
    {
        /// <summary>
        /// Main factory file template — generates TickerQInstanceFactory.g.cs
        /// </summary>
        internal const string InstanceFactory = @"// <auto-generated/>
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;

namespace {{NAMESPACE}}
{
    public static class TickerQInstanceFactoryExtensions
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        public static void Initialize()
        {
            var tickerFunctionDelegateDict = new Dictionary<string, (string, global::TickerQ.Utilities.Enums.TickerTaskPriority, global::TickerQ.Utilities.TickerFunctionDelegate, int)>({{METHOD_COUNT}})
            {
{{DELEGATE_REGISTRATIONS}}
            };
            global::TickerQ.Utilities.TickerFunctionProvider.RegisterFunctions(tickerFunctionDelegateDict, {{METHOD_COUNT}});
            RegisterRequestTypes();
            RegisterDescriptors();
        }

{{CONSTRUCTOR_METHODS}}
        private static void RegisterRequestTypes()
        {
{{REQUEST_TYPE_REGISTRATIONS}}
        }

        private static void RegisterDescriptors()
        {
{{DESCRIPTOR_REGISTRATIONS}}
        }
    }
}";

        /// <summary>
        /// Single delegate registration within Initialize()
        /// </summary>
        internal const string DelegateRegistration = @"                [{{FUNCTION_NAME}}] = ({{CRON_EXPRESSION}}, (global::TickerQ.Utilities.Enums.TickerTaskPriority){{PRIORITY}}, new global::TickerQ.Utilities.TickerFunctionDelegate({{ASYNC_KEYWORD}}(cancellationToken, serviceProvider, context) =>
                {
{{DELEGATE_BODY}}
                }), {{MAX_CONCURRENCY}}),";

        /// <summary>
        /// Constructor factory method for DI
        /// </summary>
        internal const string ConstructorMethod = @"        private static {{CLASS_NAME}} {{FACTORY_METHOD_NAME}}(IServiceProvider __serviceProvider)
        {
{{SERVICE_RESOLUTIONS}}
            return new {{CLASS_NAME}}({{CONSTRUCTOR_ARGS}});
        }
";

        /// <summary>
        /// Parameterless constructor factory method
        /// </summary>
        internal const string ParameterlessConstructorMethod = @"        private static {{CLASS_NAME}} {{FACTORY_METHOD_NAME}}(IServiceProvider __serviceProvider)
        {
            return new {{CLASS_NAME}}();
        }
";

        /// <summary>
        /// Service resolution line within constructor method
        /// </summary>
        internal const string ServiceResolution = @"            var {{PARAM_NAME}} = __serviceProvider.GetService<{{SERVICE_TYPE}}>();";

        /// <summary>
        /// Keyed service resolution line within constructor method
        /// </summary>
        internal const string KeyedServiceResolution = @"            var {{PARAM_NAME}} = __serviceProvider.GetKeyedService<{{SERVICE_TYPE}}>({{SERVICE_KEY}});";


        /// <summary>
        /// Delegate body: async instance method with generic context
        /// </summary>
        internal const string DelegateBodyAsyncGenericContext = @"                    var requestTypeInfo = global::TickerQ.Utilities.TickerFunctionProvider.GetRequestTypeInfo<{{GENERIC_TYPE}}>({{FUNCTION_NAME}});
                    var genericContext = await global::TickerQ.Utilities.TickerRequestProvider.ToGenericContextAsync<{{GENERIC_TYPE}}>(context, requestTypeInfo, cancellationToken);
                    await {{METHOD_CALL}};";

        /// <summary>
        /// Delegate body: async instance method with regular params
        /// </summary>
        internal const string DelegateBodyAsync = @"                    await {{METHOD_CALL}};";

        /// <summary>
        /// Delegate body: sync (void) instance method
        /// </summary>
        internal const string DelegateBodySync = @"                    {{METHOD_CALL}};";

        /// <summary>
        /// Request type registration block
        /// </summary>
        internal const string RequestTypeRegistration = @"            var requestTypes = new Dictionary<string, (string, Type)>({{COUNT}})
            {
{{ENTRIES}}
            };
            global::TickerQ.Utilities.TickerFunctionProvider.RegisterRequestType(requestTypes, {{COUNT}});";

        /// <summary>
        /// Single request type entry
        /// </summary>
        internal const string RequestTypeEntry = @"                [{{FUNCTION_NAME}}] = (typeof({{REQUEST_TYPE}}).FullName, typeof({{REQUEST_TYPE}})),";

        /// <summary>
        /// Deferred runtime JsonTypeInfo registration. Resolution occurs during Build(), after
        /// AddTickerQ has finalized request serializer options and any user-provided AOT context.
        /// </summary>
        internal const string RequestTypeInfoResolverRegistration = @"            var requestTypeInfoResolvers = new Dictionary<string, (Type, global::System.Func<global::System.Text.Json.JsonSerializerOptions, global::System.Text.Json.Serialization.Metadata.JsonTypeInfo>)>({{COUNT}})
            {
{{ENTRIES}}
            };
            global::TickerQ.Utilities.TickerFunctionProvider.RegisterRequestTypeInfoResolver(requestTypeInfoResolvers);";

        internal const string RequestTypeInfoResolverEntry = @"                [{{FUNCTION_NAME}}] = (typeof({{REQUEST_TYPE}}), options => options.GetTypeInfo(typeof({{REQUEST_TYPE}}))),";

        /// <summary>
        /// Canonical descriptor registration block (emitted for ALL functions).
        /// </summary>
        internal const string DescriptorRegistration = @"            var descriptors = new Dictionary<string, global::TickerQ.Utilities.Models.TickerFunctionDescriptor>({{COUNT}})
            {
{{ENTRIES}}
            };
            global::TickerQ.Utilities.TickerFunctionProvider.RegisterDescriptors(descriptors, ""source-gen"");";

        /// <summary>
        /// Descriptor entry for a typed function whose wire shape could not be inferred: the request
        /// contract carries the type name only (no schema, no example). Never a misleading schema.
        /// </summary>
        internal const string DescriptorEntryTyped = @"                [{{FUNCTION_NAME}}] = new global::TickerQ.Utilities.Models.TickerFunctionDescriptor({{FUNCTION_NAME}}, (global::TickerQ.Utilities.Enums.TickerTaskPriority){{PRIORITY}}, {{CRON_EXPRESSION}}, 1, new global::TickerQ.Utilities.Models.TickerRequestContract(typeof({{REQUEST_TYPE}}).FullName)),";

        /// <summary>
        /// Descriptor entry for a typed function with a compile-time JSON Schema 2020-12 document and one
        /// deterministic default example, both embedded as inline JSON.
        /// </summary>
        internal const string DescriptorEntryTypedWithSchema = @"                [{{FUNCTION_NAME}}] = new global::TickerQ.Utilities.Models.TickerFunctionDescriptor({{FUNCTION_NAME}}, (global::TickerQ.Utilities.Enums.TickerTaskPriority){{PRIORITY}}, {{CRON_EXPRESSION}}, 1, new global::TickerQ.Utilities.Models.TickerRequestContract(typeof({{REQUEST_TYPE}}).FullName, schemaJson: {{SCHEMA_LITERAL}}, examples: new global::TickerQ.Utilities.Models.TickerRequestExample[] { new global::TickerQ.Utilities.Models.TickerRequestExample(""default"", ""Generated example"", {{EXAMPLE_LITERAL}}) })),";

        /// <summary>Descriptor entry for a request-less function (null request).</summary>
        internal const string DescriptorEntryRequestLess = @"                [{{FUNCTION_NAME}}] = new global::TickerQ.Utilities.Models.TickerFunctionDescriptor({{FUNCTION_NAME}}, (global::TickerQ.Utilities.Enums.TickerTaskPriority){{PRIORITY}}, {{CRON_EXPRESSION}}, 1, null),";

        /// <summary>
        /// TickerFunctions.g.cs — typed function references grouped by class
        /// </summary>
        internal const string FunctionRefs = @"// <auto-generated/>
#pragma warning disable CS1591

{{ADDITIONAL_USINGS}}

namespace {{NAMESPACE}}
{
    public static class TickerFunctions
    {
{{CLASS_GROUPS}}
    }
}";

        /// <summary>
        /// Nested static class within TickerFunctions for a handler class
        /// </summary>
        internal const string FunctionRefClassGroup = @"        public static class {{CLASS_NAME}}
        {
{{REFS}}
        }
";

        /// <summary>
        /// Single typed function ref (with request type)
        /// </summary>
        internal const string FunctionRefGeneric = @"            public static readonly global::TickerQ.Utilities.TickerFunctionRef<{{REQUEST_TYPE}}> {{PROPERTY_NAME}} = new({{FUNCTION_NAME}});";

        /// <summary>
        /// Single function ref (no request type)
        /// </summary>
        internal const string FunctionRefSimple = @"            public static readonly global::TickerQ.Utilities.TickerFunctionRef {{PROPERTY_NAME}} = new({{FUNCTION_NAME}});";
    }
}
