namespace TickerQ.SourceGenerator.Generation
{
    /// <summary>
    /// Code generation templates. Each template uses {{PLACEHOLDER}} markers
    /// that are replaced at generation time with computed values.
    /// </summary>
    internal static class Templates
    {
        /// <summary>
        /// Main factory file template — generates TickerQInstanceFactory.g.cs
        /// </summary>
        internal const string InstanceFactory = @"// <auto-generated/>
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;

namespace {{NAMESPACE}}
{
    public static class TickerQInstanceFactoryExtensions
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        public static void Initialize()
        {
            var tickerFunctionDelegateDict = new Dictionary<string, (string, global::TickerQ.Utilities.Enums.TickerTaskPriority, global::TickerQ.Utilities.TickerFunctionDelegate, int)>({{METHOD_COUNT}})
            {
{{DELEGATE_REGISTRATIONS}}
            };
            global::TickerQ.Utilities.TickerFunctionProvider.RegisterFunctions(tickerFunctionDelegateDict, {{METHOD_COUNT}});
            RegisterRequestTypes();
        }

{{CONSTRUCTOR_METHODS}}
        private static void RegisterRequestTypes()
        {
{{REQUEST_TYPE_REGISTRATIONS}}
        }
    }
}";

        /// <summary>
        /// Single delegate registration within Initialize()
        /// </summary>
        internal const string DelegateRegistration = @"                [""{{FUNCTION_NAME}}""] = ({{CRON_EXPRESSION}}, (global::TickerQ.Utilities.Enums.TickerTaskPriority){{PRIORITY}}, new global::TickerQ.Utilities.TickerFunctionDelegate({{ASYNC_KEYWORD}}(cancellationToken, serviceProvider, context) =>
                {
{{DELEGATE_BODY}}
                }), {{MAX_CONCURRENCY}}),";

        /// <summary>
        /// Constructor factory method for DI
        /// </summary>
        internal const string ConstructorMethod = @"        private static {{CLASS_NAME}} {{FACTORY_METHOD_NAME}}(IServiceProvider serviceProvider)
        {
{{SERVICE_RESOLUTIONS}}
            return new {{CLASS_NAME}}({{CONSTRUCTOR_ARGS}});
        }
";

        /// <summary>
        /// Parameterless constructor factory method
        /// </summary>
        internal const string ParameterlessConstructorMethod = @"        private static {{CLASS_NAME}} {{FACTORY_METHOD_NAME}}(IServiceProvider serviceProvider)
        {
            return new {{CLASS_NAME}}();
        }
";

        /// <summary>
        /// Service resolution line within constructor method
        /// </summary>
        internal const string ServiceResolution = @"            var {{PARAM_NAME}} = serviceProvider.GetService<{{SERVICE_TYPE}}>();";

        /// <summary>
        /// Keyed service resolution line within constructor method
        /// </summary>
        internal const string KeyedServiceResolution = @"            var {{PARAM_NAME}} = serviceProvider.GetKeyedService<{{SERVICE_TYPE}}>({{SERVICE_KEY}});";


        /// <summary>
        /// Delegate body: async instance method with generic context
        /// </summary>
        internal const string DelegateBodyAsyncGenericContext = @"                    var genericContext = await global::TickerQ.Utilities.TickerRequestProvider.ToGenericContextAsync<{{GENERIC_TYPE}}>(context, cancellationToken);
                    await {{METHOD_CALL}};";

        /// <summary>
        /// Delegate body: async instance method with regular params
        /// </summary>
        internal const string DelegateBodyAsync = @"                    await {{METHOD_CALL}};";

        /// <summary>
        /// Delegate body: sync (void) instance method
        /// </summary>
        internal const string DelegateBodySync = @"                    {{METHOD_CALL}};";

        /// <summary>
        /// Request type registration block
        /// </summary>
        internal const string RequestTypeRegistration = @"            var requestTypes = new Dictionary<string, (string, Type)>({{COUNT}})
            {
{{ENTRIES}}
            };
            global::TickerQ.Utilities.TickerFunctionProvider.RegisterRequestType(requestTypes, {{COUNT}});";

        /// <summary>
        /// Single request type entry
        /// </summary>
        internal const string RequestTypeEntry = @"                [""{{FUNCTION_NAME}}""] = (typeof({{REQUEST_TYPE}}).FullName, typeof({{REQUEST_TYPE}})),";

        /// <summary>
        /// TickerFunctions.g.cs — typed function references grouped by class
        /// </summary>
        internal const string FunctionRefs = @"// <auto-generated/>
#pragma warning disable CS1591

{{ADDITIONAL_USINGS}}

namespace {{NAMESPACE}}
{
    public static class TickerFunctions
    {
{{CLASS_GROUPS}}
    }
}";

        /// <summary>
        /// Nested static class within TickerFunctions for a handler class
        /// </summary>
        internal const string FunctionRefClassGroup = @"        public static class {{CLASS_NAME}}
        {
{{REFS}}
        }
";

        /// <summary>
        /// Single typed function ref (with request type)
        /// </summary>
        internal const string FunctionRefGeneric = @"            public static readonly global::TickerQ.Utilities.TickerFunctionRef<{{REQUEST_TYPE}}> {{PROPERTY_NAME}} = new(""{{FUNCTION_NAME}}"");";

        /// <summary>
        /// Single function ref (no request type)
        /// </summary>
        internal const string FunctionRefSimple = @"            public static readonly global::TickerQ.Utilities.TickerFunctionRef {{PROPERTY_NAME}} = new(""{{FUNCTION_NAME}}"");";
    }
}
