<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(DotNetVersion)" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="$(DotNetVersion)" PrivateAssets="All" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.13" />
		<PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.12" PrivateAssets="All" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\TickerQ.SourceGenerator\TickerQ.SourceGenerator.csproj"
						  OutputItemType="Analyzer"
						  ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\..\src\TickerQ\TickerQ.csproj" />
		<ProjectReference Include="..\..\src\TickerQ.EntityFrameworkCore\TickerQ.EntityFrameworkCore.csproj" />
	</ItemGroup>

</Project>
