namespace TickerQ.Utilities
{
    /// <summary>
    /// A typed reference to a registered ticker function.
    /// Generated by the TickerQ source generator for type-safe function access.
    /// </summary>
    public readonly struct TickerFunctionRef
    {
        /// <summary>
        /// The registered function name.
        /// </summary>
        public string Name { get; }

        public TickerFunctionRef(string name)
        {
            Name = name;
        }

        public override string ToString() => Name;

        public static implicit operator string(TickerFunctionRef r) => r.Name;
    }

    /// <summary>
    /// A typed reference to a registered ticker function with a known request type.
    /// Generated by the TickerQ source generator for type-safe function access.
    /// </summary>
    /// <typeparam name="TRequest">The request payload type for this function.</typeparam>
    public readonly struct TickerFunctionRef<TRequest>
    {
        /// <summary>
        /// The registered function name.
        /// </summary>
        public string Name { get; }

        public TickerFunctionRef(string name)
        {
            Name = name;
        }

        public override string ToString() => Name;

        public static implicit operator string(TickerFunctionRef<TRequest> r) => r.Name;
    }
}
