name: Publish NuGet Packages

env:
  DOTNET_NOLOGO: true

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production-publish

    steps:
      - name: Download nupkgs
        uses: actions/download-artifact@v4
        with:
          name: nupkgs
          path: ./nupkgs

      - name: Push to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          VERSION=${{ inputs.version }}
          check_and_push() {
            PACKAGE_NAME=$1
            PACKAGE_FILE=$2
            EXISTS=$(curl -s -o /dev/null -w "%{http_code}" \
              "https://api.nuget.org/v3-flatcontainer/${PACKAGE_NAME,,}/$VERSION/${PACKAGE_NAME,,}.$VERSION.nupkg")

            if [ "$EXISTS" == "200" ]; then
              echo "$PACKAGE_NAME $VERSION already exists. Skipping."
            else
              echo "Pushing $PACKAGE_NAME $VERSION..."
              dotnet nuget push "$PACKAGE_FILE" --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
            fi
          }

          for file in ./nupkgs/*.nupkg; do
            fname=$(basename "$file")
            if [[ "$fname" == TickerQ.Utilities.*.nupkg ]]; then
              check_and_push "TickerQ.Utilities" "$file"
            elif [[ "$fname" == TickerQ.EntityFrameworkCore.*.nupkg ]]; then
              check_and_push "TickerQ.EntityFrameworkCore" "$file"
            elif [[ "$fname" == TickerQ.Dashboard.*.nupkg ]]; then
              check_and_push "TickerQ.Dashboard" "$file"
            elif [[ "$fname" == TickerQ.*.nupkg ]]; then
              check_and_push "TickerQ" "$file"
            fi
          done
